### PR TITLE
Globalize ``package`` and ``require`` so it persists, and create ``shell.append_path`` setting.

### PR DESCRIPTION
**Pull request by Apethesis**
This is useful for OSes and stuff like unicornpkg cause then you could set shell.append_path to ``;/lib/?.lua;/lib/?/init.lua`` and then do require("cimg2") instead of require("lib.cimg2").

### CODE REVIEW

**Comment by Wojbie** [comment]
Those changes seem to be incompatible with backwards compatibility ideas of CC:T.

**Comment by Apethesis** [comment]
Backwards compatibility ideas?

**Comment by 9551-Dev** [comment]
:moyai:

**Comment by Apethesis** [comment]
fair enough

**Comment by Apethesis** [comment]
Squid what made you close it without a comment, the globalization?
I could always just undo that

**Comment by tomodachi94** [comment]
For posterity, here's the "backwards compatibility concerns," as phrased by @Wojbie in the MCCM Discord:
>  Moved require and its chidren parts from shell env into _G and changes in require logic. Both that would make code that expects require to be CC vanilla to break.

**Comment by SquidDev** [comment]
> Squid what made you close it without a comment 

SC is the wrong place to change this - the patches applied to CC's rom aim to be as minimal as possible, to make maintenance easier. 

As far as the original issue goes, this has been discussed to death (i.e. https://github.com/cc-tweaked/CC-Tweaked/issues/739)

**Pull request closed without merging**
